### ISSUE TITLE
okay i have a question using this will not have any oracle policy violation or something 

### ISSUE THREAD

**Issue by balsikandar** [dmstocking/support-optional#2]
I checked couple of articles where these questions were raised so?

**Comment by dmstocking** [comment]
So none of the "code" is oracle code. I did however copy the documentation so that it would be the same as the real JDK versions. I don't know exactly how that works. I am pretty sure I copied the OpenJDK version. I would suspect that OpenJDK and Oracle JDK both have the same documentation because that is a specification for Java 7/8/9. There is a support stream library that literally copies Oracle code. I do not think that is legal at all. That is why I specifically wrote the code to try and avoid this problem. I don't talk about it much, but I did write a blog post about this https://medium.com/@dmstocking/choosing-an-optional-backport-5f03fa7d35ce.

EDIT: BTW what did you read that made you question this? I would always like to keep up on licenses and stuff like that.

**Comment by balsikandar** [comment]
I was digging around for any Optional support libraries and i read few articles and in one such article there was a line about licensing and stuff, So i decided to just clarify before using this. Well thanks for your work i'm using this project in my app now.
